name: 💡 Feature request / suggestion
description: Suggest an idea or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Your idea
      description: What would you like to see in the app?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is it useful?
      description: How would this help you or other bakers?
